language: python
python: "2.7"
install:
  - pip install -r requirements.txt
script:  python test.py
services:
  - postgresql
  - mysql

addons:
  postgresql: "9.6"
before_script:
  - psql -c 'drop database if exists travis_ci_test;' -U postgres
  - psql -c 'drop schema if exists logging;' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create schema logging;' -U postgres
  - psql -c "CREATE USER tester WITH PASSWORD 'test';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA logging TO tester;" -U postgres


  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('test') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
before_install:
  - sudo apt-get update
  - sudo apt-get install python-requests -y

after_script:
  - psql -c 'drop schema logging cascade;' -U postgres
  - psql -c 'drop database travis_ci_test cascade;' -U postgres
