language: python
python: "3.6"
install:
  - pip install -r requirements.txt
script:  python test.py
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'drop database if exists travis_ci_test;' -U postgres
  - psql -c 'drop schema if exists coin_test;' -U postgres
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'create schema coin_test;' -U postgres
before_install:
  - sudo apt-get update
  - sudo apt-get install python-requests -y
after_script:
  - psql -c 'drop schema coin_test;' -U postgres
  - psql -c 'drop database travis_ci_test;' -U postgres
