language: python
sudo: false
python:
  - "3.6"
  #- "2.7"
script: 'pipenv run pytest tests'
env:
  PGDATABASE: postgres
  PGUSER: postgres
  PGPASSWORD: docker
  PGPORT: 55432
  MYSQL_DATABASE: mysql
  MYSQL_USER: root
  MYSQL_PASSWORD: docker
  MYSQL_PORT: 33306    
  
#script: 'pipenv run pytest --cov=pyblizzard tests --cov-report=xml'
services:
  - docker
before_install:
  #- docker run -d --name mssql-express -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Docker1234' -e 'MSSQL_PID=Express' -p 11433:1433 mcr.microsoft.com/mssql/server:2017-latest-ubuntu
  - docker pull postgres
  - docker pull mariadb
  - docker run -d -p 55432:5432 -e POSTGRES_PASSWORD=docker -d postgres
  - docker run -d -p 33306:3306 -e MYSQL_ROOT_PASSWORD=docker -d mariadb

install:
  - pip install pipenv
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - pipenv install --dev