version: '2'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER:'foo'
      - POSTGRES_PASSWORD:'foobar'
      - POSTGRES_DB:'test'
    ports:
      - "5432:5432"
    restart: unless-stopped
#  mysql:
#    image: mysql
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: "test"
