version: '2'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "test"
