version: '3'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ..:/workspace
      # This lets you avoid setting up Git again in the container
      - ~/.gitconfig:/root/.gitconfig

    # Overrides default command so things don't shut down after the process ends - useful for debugging
    command: sleep infinity
    links:
      - pgdb
      - mysqldb
      - mssqldb
    environment:
      PGHOST: pgdb1
      PGDATABASE: postgres
      PGUSER: docker
      PGPASSWORD: docker
      PYTHONPATH: /workspace/src
      PGPORT: 5432
      MYSQL_DATABASE: test
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_HOST: mysqldb1
      MYSQL_PORT: 3306    
      MS_PASSWORD: Docker1234
      MS_PORT: 1433
      MS_HOST: mssqldb1
      MS_USER: sa
      MS_DATABASE: master
  pgdb:
    image: postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
  mysqldb:
    image: mariadb
    restart: always
    ports: 
      - 3306:3306

    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: test
        MYSQL_USER: docker
        MYSQL_PASSWORD: docker
        MYSQL_HOST: mysqldb
        MYSQL_PORT: 3306
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: always
    ports: 
      - 1433:1433
    environment:
        ACCEPT_EULA: 'Y'
        SA_PASSWORD: Docker1234
        MSSQL_PID: Express
        
 